export type TestCategory = 'security' | 'api' | 'llm' | 'navigation' | 'production';
export type TestSeverity = 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'INFO' | 'LOW';
export type TestStatus = 'pending' | 'running' | 'passed' | 'failed' | 'skipped';

export interface TestCaseDefinition {
    id: string;
    title: string;
    category: TestCategory;
    severity: TestSeverity;
    description: string;
    expected: string;
    runner: 'client' | 'server';
    action: string;
}

export interface TestResult {
    id: string;
    status: TestStatus;
    durationMs: number;
    assertions: {
        name: string;
        passed: boolean;
        expected?: any;
        actual?: any;
        message?: string;
    }[];
    request?: {
        method: string;
        url: string;
        body?: any;
        headers?: Record<string, string>;
    };
    response?: {
        status?: number;
        statusText?: string;
        body?: any;
        headers?: Record<string, string>;
    };
    error?: string;
}

export const TEST_DEFINITIONS: TestCaseDefinition[] = [
    // ══════════════════════════════════════════════════════════════════════════
    // CATEGORY 1: SECURITY & VULNERABILITY (12 Tests)
    // ══════════════════════════════════════════════════════════════════════════
    {
        id: 'SEC-01',
        title: 'Admin Middleware Route Protection',
        category: 'security',
        severity: 'CRITICAL',
        description: 'Verify Next.js middleware immediately halts unauthenticated access to /api/admin/* with 401 Unauthorized.',
        expected: 'HTTP 401 Unauthorized with error message',
        runner: 'server',
        action: 'sec_admin_no_cookie',
    },
    {
        id: 'SEC-02',
        title: 'Forged Admin Session Cookie Defense',
        category: 'security',
        severity: 'CRITICAL',
        description: 'Verify middleware rejects forged or invalid admin_session cookie values without DB leak.',
        expected: 'HTTP 401 Unauthorized',
        runner: 'server',
        action: 'sec_admin_forged_cookie',
    },
    {
        id: 'SEC-03',
        title: 'Public Admin Login Route Whitelist',
        category: 'security',
        severity: 'HIGH',
        description: 'Verify public admin login endpoint /api/admin/auth/login is exempted by middleware and reachable without pre-existing session.',
        expected: 'HTTP 200 or 400 (not blocked by 401 middleware)',
        runner: 'server',
        action: 'sec_admin_login_accessible',
    },
    {
        id: 'SEC-04',
        title: 'Prompt Injection System-Override Resistance',
        category: 'security',
        severity: 'CRITICAL',
        description: 'Send adversarial jailbreak prompt attempting to override system directives and leak developer prompts or internal instructions.',
        expected: 'Refusal or safe quantum identity response, zero system prompt or secret leakage',
        runner: 'server',
        action: 'sec_prompt_injection_override',
    },
    {
        id: 'SEC-05',
        title: 'Model Identity Guardrail Masking',
        category: 'security',
        severity: 'HIGH',
        description: 'Probe AI identity to verify provider masking guardrails prevent leaking underlying model name or infrastructure details.',
        expected: 'Sanitized identity response maintaining Quantum Guru AI branding',
        runner: 'server',
        action: 'sec_identity_guardrail',
    },
    {
        id: 'SEC-06',
        title: 'XSS HTML/Script Injection Neutralization',
        category: 'security',
        severity: 'CRITICAL',
        description: 'Send malicious XSS payload (<script>alert(1)</script><img src=x onerror=...>) and verify output is escaped or sanitized.',
        expected: 'No executable script execution, safely encoded in response',
        runner: 'server',
        action: 'sec_xss_sanitization',
    },
    {
        id: 'SEC-07',
        title: 'Path Traversal Attack Defense',
        category: 'security',
        severity: 'CRITICAL',
        description: 'Attempt directory traversal attacks (../../../../etc/passwd) on file and project query parameters.',
        expected: 'Validation rejection or 400/404, never disclosing filesystem contents',
        runner: 'server',
        action: 'sec_path_traversal',
    },
    {
        id: 'SEC-08',
        title: 'NoSQL Operator Injection Defense',
        category: 'security',
        severity: 'CRITICAL',
        description: 'Submit MongoDB query injection payloads ({"$gt": ""}) to authentication endpoint to verify parameter sanitization.',
        expected: 'HTTP 400/401 invalid credentials, no authentication bypass',
        runner: 'server',
        action: 'sec_nosql_injection',
    },
    {
        id: 'SEC-09',
        title: 'Unauthenticated User Session Guard',
        category: 'security',
        severity: 'HIGH',
        description: 'Query /api/auth/me without user session cookies to ensure no state or data leaks to anonymous clients.',
        expected: 'HTTP 401 or null user object',
        runner: 'server',
        action: 'sec_auth_me_unauth',
    },
    {
        id: 'SEC-10',
        title: 'Unauthenticated Password Change Guard',
        category: 'security',
        severity: 'CRITICAL',
        description: 'Verify /api/auth/change-password rejects requests lacking verified authentication session.',
        expected: 'HTTP 401 Unauthorized',
        runner: 'server',
        action: 'sec_password_change_unauth',
    },
    {
        id: 'SEC-11',
        title: 'API Secret & Environment Leakage Scan',
        category: 'security',
        severity: 'CRITICAL',
        description: 'Scan API responses to ensure sensitive env tokens (GROQ_API_KEY, MONGODB_URI, ADMIN_SESSION_SECRET) are never leaked.',
        expected: 'Zero secret keys exposed in responses',
        runner: 'server',
        action: 'sec_secret_leakage_scan',
    },
    {
        id: 'SEC-12',
        title: 'Security & Cache-Control Headers Verification',
        category: 'security',
        severity: 'MEDIUM',
        description: 'Verify essential security headers (Cache-Control: no-store on sensitive routes, Vary, X-Content-Type-Options).',
        expected: 'Security headers present on API responses',
        runner: 'server',
        action: 'sec_security_headers',
    },

    // ══════════════════════════════════════════════════════════════════════════
    // CATEGORY 2: API & ENDPOINT ROBUSTNESS (12 Tests)
    // ══════════════════════════════════════════════════════════════════════════
    {
        id: 'API-01',
        title: 'Quantum AI Engine Health Check',
        category: 'api',
        severity: 'CRITICAL',
        description: 'Verify Quantum AI Engine (:8003) is healthy, running in Groq mode with active Qwen model.',
        expected: 'HTTP 200 with status: ok, mode: groq',
        runner: 'server',
        action: 'api_engine_health',
    },
    {
        id: 'API-02',
        title: 'API Gateway Health Check',
        category: 'api',
        severity: 'CRITICAL',
        description: 'Verify API Gateway (:8002) is responsive and healthy.',
        expected: 'HTTP 200 with status: ok',
        runner: 'server',
        action: 'api_gateway_health',
    },
    {
        id: 'API-03',
        title: 'Malformed JSON Payload Handling',
        category: 'api',
        severity: 'HIGH',
        description: 'Send unparseable raw JSON ({"broken": ) to API endpoint and verify graceful 400 Bad Request error.',
        expected: 'HTTP 400 Bad Request, no server crash',
        runner: 'server',
        action: 'api_malformed_json',
    },
    {
        id: 'API-04',
        title: 'Empty POST Body Tolerance',
        category: 'api',
        severity: 'MEDIUM',
        description: 'Send empty JSON payload ({}) to solver endpoint and verify structured validation error.',
        expected: 'HTTP 400 or 422 with structured error message',
        runner: 'server',
        action: 'api_empty_body',
    },
    {
        id: 'API-05',
        title: 'Non-Existent Route 404 Handling',
        category: 'api',
        severity: 'INFO',
        description: 'Send request to non-existent API route /api/nonexistent-endpoint-xyz.',
        expected: 'HTTP 404 with clean response',
        runner: 'server',
        action: 'api_nonexistent_route',
    },
    {
        id: 'API-06',
        title: 'Disallowed HTTP Method Handling',
        category: 'api',
        severity: 'MEDIUM',
        description: 'Send unsupported DELETE method to /api/auth/login.',
        expected: 'HTTP 405 Method Not Allowed',
        runner: 'server',
        action: 'api_disallowed_method',
    },
    {
        id: 'API-07',
        title: 'Massive Input Payload Guard',
        category: 'api',
        severity: 'HIGH',
        description: 'Send 25,000+ character string to test token guard and buffer handling without memory overflow.',
        expected: 'Graceful token budget warning or truncation, no server crash',
        runner: 'server',
        action: 'api_massive_payload',
    },
    {
        id: 'API-08',
        title: 'Unicode & Quantum Dirac Math Handling',
        category: 'api',
        severity: 'HIGH',
        description: 'Submit complex quantum bra-ket notation and unicode symbols: |ψ⟩ = α|0⟩ + β|1⟩, ∑, ∫, Ω, ⚛️.',
        expected: 'Characters preserved accurately without encoding errors',
        runner: 'server',
        action: 'api_unicode_dirac',
    },
    {
        id: 'API-09',
        title: 'Null & Undefined Field Tolerance',
        category: 'api',
        severity: 'MEDIUM',
        description: 'Send payload with null and undefined required fields to test schema resilience.',
        expected: 'Validation error response, no unhandled exception',
        runner: 'server',
        action: 'api_null_fields',
    },
    {
        id: 'API-10',
        title: 'Quantum Hardware Catalog Endpoint',
        category: 'api',
        severity: 'HIGH',
        description: 'Query /api/hardware to verify quantum processor backends catalog returns valid array.',
        expected: 'HTTP 200 with valid backend definitions',
        runner: 'server',
        action: 'api_hardware_catalog',
    },
    {
        id: 'API-11',
        title: 'Quantum IDE Projects Endpoint',
        category: 'api',
        severity: 'HIGH',
        description: 'Query /api/ide/projects to verify workspace project schema and structure.',
        expected: 'HTTP 200 with projects array',
        runner: 'server',
        action: 'api_ide_projects',
    },
    {
        id: 'API-12',
        title: 'Rapid-Fire Request Concurrency',
        category: 'api',
        severity: 'HIGH',
        description: 'Fire 3 simultaneous requests to verify connection pool handles concurrency cleanly.',
        expected: 'All 3 requests complete with valid HTTP status',
        runner: 'server',
        action: 'api_concurrency_burst',
    },

    // ══════════════════════════════════════════════════════════════════════════
    // CATEGORY 3: AI REASONING & GROQ INFERENCE INTEGRITY (10 Tests)
    // ══════════════════════════════════════════════════════════════════════════
    {
        id: 'LLM-01',
        title: 'Live Quantum Assistant Chat Completion',
        category: 'llm',
        severity: 'CRITICAL',
        description: 'Submit quantum computing query to /engine/assistant/chat and verify valid markdown response.',
        expected: 'HTTP 200 with substantive markdown response',
        runner: 'server',
        action: 'llm_assistant_chat_live',
    },
    {
        id: 'LLM-02',
        title: 'Truncation Prevention Verification',
        category: 'llm',
        severity: 'CRITICAL',
        description: 'Verify multi-step technical query generates comprehensive response (> 1,200 chars) without truncation.',
        expected: 'Complete response with finish_reason != length and length > 1,200 chars',
        runner: 'server',
        action: 'llm_truncation_prevention',
    },
    {
        id: 'LLM-03',
        title: 'Markdown Code Block Fence Integrity',
        category: 'llm',
        severity: 'HIGH',
        description: 'Verify all code blocks in LLM responses have matching opening and closing ``` fences.',
        expected: 'Even count of ``` markers (all code blocks properly closed)',
        runner: 'server',
        action: 'llm_code_fences_integrity',
    },
    {
        id: 'LLM-04',
        title: 'LaTeX Dirac Notation Formatting',
        category: 'llm',
        severity: 'HIGH',
        description: 'Verify mathematical and quantum notation employs valid KaTeX/LaTeX formatting ($...$).',
        expected: 'Contains valid LaTeX math expressions ($|...\rangle$)',
        runner: 'server',
        action: 'llm_latex_math_formatting',
    },
    {
        id: 'LLM-05',
        title: 'Qiskit Circuit Code Synthesis',
        category: 'llm',
        severity: 'CRITICAL',
        description: 'Request Bell state circuit synthesis and verify valid Qiskit Python code is produced.',
        expected: 'Valid Qiskit script with QuantumCircuit, h, cx gates',
        runner: 'server',
        action: 'llm_qiskit_synthesis',
    },
    {
        id: 'LLM-06',
        title: 'Model Configuration & Think Tag Suppression',
        category: 'llm',
        severity: 'HIGH',
        description: 'Verify active model is Qwen 3.6 27B and <think> reasoning tags are suppressed from output.',
        expected: 'No <think> or </think> tags visible in user response',
        runner: 'server',
        action: 'llm_model_think_suppression',
    },
    {
        id: 'LLM-07',
        title: 'Empty Prompt Input Validation',
        category: 'llm',
        severity: 'MEDIUM',
        description: 'Send whitespace-only prompt to assistant and verify validation error or prompt prompt.',
        expected: 'Graceful prompt rejection or prompt for clarification',
        runner: 'server',
        action: 'llm_empty_prompt',
    },
    {
        id: 'LLM-08',
        title: 'Direct Model Optimization Endpoint',
        category: 'llm',
        severity: 'HIGH',
        description: 'Test direct model solve endpoint /api/direct-model/solve for optimization tasks.',
        expected: 'HTTP 200 or structured error, active endpoint',
        runner: 'server',
        action: 'llm_optimization_endpoint',
    },
    {
        id: 'LLM-09',
        title: 'Groq Inference Latency SLA Bound',
        category: 'llm',
        severity: 'MEDIUM',
        description: 'Verify standard Groq inference completes within reasonable SLA (< 15 seconds).',
        expected: 'Response received in < 15,000ms',
        runner: 'server',
        action: 'llm_inference_latency_sla',
    },
    {
        id: 'LLM-10',
        title: 'Response Completeness Directive Check',
        category: 'llm',
        severity: 'HIGH',
        description: 'Verify response terminates cleanly with full sentence or code conclusion rather than mid-word.',
        expected: 'Last character is terminal punctuation or closing code fence',
        runner: 'server',
        action: 'llm_completeness_directive',
    },

    // ══════════════════════════════════════════════════════════════════════════
    // CATEGORY 4: FRONTEND STATE & NAVIGATION RESILIENCE (8 Tests)
    // ══════════════════════════════════════════════════════════════════════════
    {
        id: 'NAV-01',
        title: 'Home Page Route (/)',
        category: 'navigation',
        severity: 'HIGH',
        description: 'Verify the landing page / renders with HTTP 200 and complete HTML layout.',
        expected: 'HTTP 200 OK with HTML document',
        runner: 'client',
        action: 'nav_home_page',
    },
    {
        id: 'NAV-02',
        title: 'Quantum IDE Page Route (/ide)',
        category: 'navigation',
        severity: 'CRITICAL',
        description: 'Verify Quantum IDE workspace /ide loads with HTTP 200.',
        expected: 'HTTP 200 OK',
        runner: 'client',
        action: 'nav_ide_page',
    },
    {
        id: 'NAV-03',
        title: 'Quantum Assistant Route (/quantum-assistant)',
        category: 'navigation',
        severity: 'CRITICAL',
        description: 'Verify Quantum Assistant chat interface /quantum-assistant loads with HTTP 200.',
        expected: 'HTTP 200 OK',
        runner: 'client',
        action: 'nav_assistant_page',
    },
    {
        id: 'NAV-04',
        title: 'Capabilities Route (/quantum-assistant/capabilities)',
        category: 'navigation',
        severity: 'MEDIUM',
        description: 'Verify assistant capabilities catalog /quantum-assistant/capabilities loads with HTTP 200.',
        expected: 'HTTP 200 OK',
        runner: 'client',
        action: 'nav_capabilities_page',
    },
    {
        id: 'NAV-05',
        title: 'Admin Login Route (/admin/login)',
        category: 'navigation',
        severity: 'HIGH',
        description: 'Verify Admin login portal /admin/login loads with HTTP 200.',
        expected: 'HTTP 200 OK',
        runner: 'client',
        action: 'nav_admin_login_page',
    },
    {
        id: 'NAV-06',
        title: 'User Login Route (/login)',
        category: 'navigation',
        severity: 'HIGH',
        description: 'Verify User login portal /login loads with HTTP 200.',
        expected: 'HTTP 200 OK',
        runner: 'client',
        action: 'nav_user_login_page',
    },
    {
        id: 'NAV-07',
        title: 'Marketplace Route (/marketplace)',
        category: 'navigation',
        severity: 'MEDIUM',
        description: 'Verify Marketplace catalog /marketplace loads with HTTP 200.',
        expected: 'HTTP 200 OK',
        runner: 'client',
        action: 'nav_marketplace_page',
    },
    {
        id: 'NAV-08',
        title: 'Client State & Corrupted LocalStorage Resilience',
        category: 'navigation',
        severity: 'HIGH',
        description: 'Verify client UI handles malformed or corrupted localStorage values without crashing.',
        expected: 'Safe recovery with fallback defaults, no uncaught JS error',
        runner: 'client',
        action: 'nav_corrupted_localstorage',
    },

    // ══════════════════════════════════════════════════════════════════════════
    // CATEGORY 5: PRODUCTION READINESS & PERFORMANCE (10 Tests)
    // ══════════════════════════════════════════════════════════════════════════
    {
        id: 'PERF-01',
        title: 'AI Engine Health Latency Benchmark',
        category: 'production',
        severity: 'HIGH',
        description: 'Verify Quantum AI Engine (:8003) health probe responds within < 150ms.',
        expected: 'Latency < 150ms',
        runner: 'server',
        action: 'perf_engine_latency',
    },
    {
        id: 'PERF-02',
        title: 'API Gateway Health Latency Benchmark',
        category: 'production',
        severity: 'HIGH',
        description: 'Verify API Gateway (:8002) health probe responds within < 250ms.',
        expected: 'Latency < 250ms',
        runner: 'server',
        action: 'perf_gateway_latency',
    },
    {
        id: 'PERF-03',
        title: 'Next.js Frontend SSR Latency Benchmark',
        category: 'production',
        severity: 'MEDIUM',
        description: 'Verify Next.js frontend pages respond within < 1,000ms on initial request.',
        expected: 'Latency < 1000ms',
        runner: 'server',
        action: 'perf_frontend_latency',
    },
    {
        id: 'PERF-04',
        title: 'Error Response Schema Standardization',
        category: 'production',
        severity: 'HIGH',
        description: 'Verify API errors return consistent JSON objects containing an error or message field.',
        expected: 'Consistent { error: string } or { message: string } schema',
        runner: 'server',
        action: 'perf_error_schema',
    },
    {
        id: 'PERF-05',
        title: 'Zero Internal Stack Trace Leakage',
        category: 'production',
        severity: 'CRITICAL',
        description: 'Verify errors do not expose file paths, Python tracebacks, or system internals to clients.',
        expected: 'No "Traceback (most recent call last)" or file path leaks in client errors',
        runner: 'server',
        action: 'perf_no_stack_traces',
    },
    {
        id: 'PERF-06',
        title: 'Concurrent Gateway Request Resilience',
        category: 'production',
        severity: 'HIGH',
        description: 'Send 4 parallel requests to the gateway to ensure connection pool does not deadlock.',
        expected: 'All 4 requests succeed simultaneously',
        runner: 'server',
        action: 'perf_concurrent_gateway',
    },
    {
        id: 'PERF-07',
        title: 'HTTP Compression Header Verification',
        category: 'production',
        severity: 'MEDIUM',
        description: 'Verify frontend responses support modern compression formats (gzip, br, deflate).',
        expected: 'Accept-Encoding / Content-Encoding support verified',
        runner: 'server',
        action: 'perf_compression_headers',
    },
    {
        id: 'PERF-08',
        title: 'Production Environment Mode Verification',
        category: 'production',
        severity: 'HIGH',
        description: 'Verify AI Engine is operating with pure Groq LLM inference without deprecated dependencies.',
        expected: 'Inference provider == "groq" and primary model loaded',
        runner: 'server',
        action: 'perf_env_sanity',
    },
    {
        id: 'PERF-09',
        title: 'Sequential Request Memory & Latency Stability',
        category: 'production',
        severity: 'MEDIUM',
        description: 'Execute 5 rapid health requests in sequence to verify latency variance remains under 200ms.',
        expected: 'Stable sequential latencies, stddev within normal limits',
        runner: 'server',
        action: 'perf_burst_stability',
    },
    {
        id: 'PERF-10',
        title: 'Test Audit Report Generation & Export',
        category: 'production',
        severity: 'INFO',
        description: 'Verify entire test suite results can be converted into valid JSON and Markdown audit reports.',
        expected: 'Structured audit export with 100% test case coverage',
        runner: 'client',
        action: 'perf_export_audit',
    },
    // ══════════════════════════════════════════════════════════════════════════
    // CATEGORY 6: D-WAVE ANNEALING WORKFLOW (PHASE 2) (3 Tests)
    // ══════════════════════════════════════════════════════════════════════════
    {
        id: 'DWAVE-01',
        title: 'User BQM Execution on Local Annealer',
        category: 'api',
        severity: 'CRITICAL',
        description: 'Verify user-written Binary Quadratic Model executes in IDE sandbox on dwave_simulated_annealing and returns optimal energy and bitstrings.',
        expected: 'HTTP 200 with energy: -1.0, backend_used: dwave_simulated_annealing',
        runner: 'server',
        action: 'dwave_user_code_execute',
    },
    {
        id: 'DWAVE-02',
        title: 'AI Explanation of User-Written D-Wave Code',
        category: 'llm',
        severity: 'HIGH',
        description: 'Verify AI Copilot analyzes and explains user-provided QUBO/BQM code in the active editor.',
        expected: 'Substantive explanation of BQM variables, energy function, and ground state',
        runner: 'server',
        action: 'dwave_ai_code_explanation',
    },
    {
        id: 'DWAVE-03',
        title: 'Autonomous Synthesis Guardrail (Phase 3 Notice)',
        category: 'security',
        severity: 'HIGH',
        description: 'Verify AI Copilot declines requests to autonomously synthesize complete D-Wave scripts from scratch, deferring to Phase 3.',
        expected: 'Decline notice citing Phase 3 autonomous synthesis roadmap',
        runner: 'server',
        action: 'dwave_autonomous_refusal_guardrail',
    },
    {
        id: 'DWAVE-04',
        title: 'Cloud QPU Fallback Interception',
        category: 'api',
        severity: 'HIGH',
        description: 'Verify user-pasted code invoking cloud DWaveSampler without Leap credentials gracefully falls back to local SimulatedAnnealingSampler with informative banner.',
        expected: 'HTTP 200 with cloud_rerouted: true and offline fallback banner',
        runner: 'server',
        action: 'dwave_cloud_fallback_intercept',
    },
];
