"""
DCC — Dynamic Constraint Compilation (Deterministic Fallback)
QuantumGuru Engine v2 — Compiler Module

This module is the safety net of the entire pipeline.
If the LLM Code Generator fails QA, DCC deterministically compiles
the parsed IR into mathematically correct CQM Python code.
No LLM involved — pure Python logic. Always works.
"""


def compile_to_cqm_code(ir: dict) -> str:
    """
    Deterministically compile IR dict into valid D-Wave dimod CQM Python code.
    
    Args:
        ir: Parsed intermediate representation from NLP Parser step
            Expected keys: entities_count, slots_count, capacity_val,
                           entities_name, slots_name, capacity_type, uniqueness_val
    Returns:
        Valid Python code string using dimod.ConstrainedQuadraticModel
    """
    e_cnt  = ir.get("entities_count", 1)
    s_cnt  = ir.get("slots_count", 1)
    cap    = ir.get("capacity_val") or 1
    e_name = ir.get("entities_name", "worker")
    s_name = ir.get("slots_name", "slot")
    cap_type = ir.get("capacity_type", "upper_bound")
    uniq   = ir.get("uniqueness_val") or 1

    # Build constraint operator based on type
    cap_op = "<=" if cap_type == "upper_bound" else (">=" if cap_type == "lower_bound" else "==")

    lines = [
        "import dimod",
        "",
        f"# DCC-generated CQM: {e_cnt} {e_name}(s) x {s_cnt} {s_name}(s)",
        f"# Generated by QuantumGuru DCC Deterministic Compiler",
        "",
        "cqm = dimod.ConstrainedQuadraticModel()",
        "",
        f"# Binary decision variables: x[i][j] = 1 if {e_name} i assigned to {s_name} j",
        f"x = {{(i, j): dimod.Binary(f'x_{{i}}_{{j}}') for i in range({e_cnt}) for j in range({s_cnt})}}",
        "",
        f"# Capacity constraint: each {s_name} gets {cap_op} {cap} {e_name}(s)",
        f"for j in range({s_cnt}):",
        f"    cqm.add_constraint(",
        f"        sum(x[i, j] for i in range({e_cnt})) {cap_op} {cap},",
        f"        label=f'{s_name}_capacity_{{j}}'",
        f"    )",
        "",
        f"# Uniqueness constraint: each {e_name} assigned to exactly {uniq} {s_name}(s)",
        f"for i in range({e_cnt}):",
        f"    cqm.add_constraint(",
        f"        sum(x[i, j] for j in range({s_cnt})) == {uniq},",
        f"        label=f'{e_name}_assignment_{{i}}'",
        f"    )",
        "",
        "# Objective: minimize total assignments (can be customized)",
        f"cqm.set_objective(-sum(x[i, j] for i in range({e_cnt}) for j in range({s_cnt})))",
        "",
        "# Verification",
        "print(f'CQM built successfully.')",
        "print(f'Variables  : {{len(cqm.variables)}}')",
        "print(f'Constraints: {{len(cqm.constraints)}}')",
        f"print(f'Problem    : {e_cnt} {e_name}s x {s_cnt} {s_name}s, capacity {cap_op} {cap}')",
    ]
    return "\n".join(lines)


def audit_cqm_code(code: str, constraints: list) -> str:
    """
    Audit generated CQM code for common errors.
    
    Returns:
        "PASS: ..." if code looks valid
        "FAIL: ..." with description if issues found
    """
    issues = []

    if not code or len(code.strip()) < 10:
        return "FAIL: Empty or trivial code generated"

    if "MLX_ERROR" in code or "QWEN_ERROR" in code:
        return "FAIL: LLM generation error in code"

    # Check for essential CQM elements
    checks = [
        ("import dimod",          "Missing: import dimod"),
        ("ConstrainedQuadraticModel", "Missing: CQM instantiation"),
        ("add_constraint",        "Missing: add_constraint calls"),
        ("set_objective",         "Missing: set_objective call"),
    ]
    for token, msg in checks:
        if token not in code:
            issues.append(msg)

    # Syntax check
    try:
        compile(code, "<generated>", "exec")
    except SyntaxError as e:
        issues.append(f"SyntaxError at line {e.lineno}: {e.msg}")

    if issues:
        return "FAIL: " + " | ".join(issues)
    return f"PASS: Code passed QA audit. CQM structure valid. ({len(code.splitlines())} lines)"


def audit_ortools_code(code: str) -> str:
    """Audit generated OR-Tools CP-SAT code."""
    if not code or len(code.strip()) < 10:
        return "FAIL: Empty or trivial code"
    if "MLX_ERROR" in code or "QWEN_ERROR" in code:
        return "FAIL: LLM generation error"

    checks = [
        ("from ortools",    "Missing: ortools import"),
        ("CpModel",         "Missing: CpModel usage"),
        ("CpSolver",        "Missing: CpSolver usage"),
        ("Solve",           "Missing: solver.Solve() call"),
    ]
    issues = []
    for token, msg in checks:
        if token not in code:
            issues.append(msg)
    try:
        compile(code, "<generated>", "exec")
    except SyntaxError as e:
        issues.append(f"SyntaxError: {e.msg}")

    if issues:
        return "FAIL: " + " | ".join(issues)
    return "PASS: OR-Tools code structure valid."
